In [1]:
import pandas as pd

In [5]:
df = pd.read_csv('./nycflights13.csv.bz2', '\t')

In [8]:
df.columns

Index(['year', 'month', 'day', 'dep_time', 'sched_dep_time', 'dep_delay',
       'arr_time', 'sched_arr_time', 'arr_delay', 'carrier', 'flight',
       'tailnum', 'origin', 'dest', 'air_time', 'distance', 'hour', 'minute',
       'time_hour'],
      dtype='object')

The variables in the dataset are 'year', 'month', 'day', 'dep_time', 'sched_dep_time', 'dep_delay', 'arr_time', 'sched_arr_time', 'arr_delay', 'carrier', 'flight', 'tailnum', 'origin', 'dest', 'air_time', 'distance', 'hour', 'minute', and 'time_hour'

In [11]:
df.shape

(336776, 19)

There were 336776 flights out of NYC in 2013

In [14]:
df.origin.value_counts()

EWR    120835
JFK    111279
LGA    104662
Name: origin, dtype: int64

There are 3 NYC airports in this data: EWR, JFK, LGA

In [15]:
df.dest.nunique()

105

The airlines flew into 105 airports

In [17]:
df[df['dest'] == 'SEA'].shape

(3923, 19)

There were 3923 flights from NYC to Seattle

In [18]:
df[df['dest'] == 'GEG'].shape

(0, 19)

There were no flights from NYC to Spokane

In [20]:
df.dest.str.match('[A-Z]{3}$').value_counts()

True    336776
Name: dest, dtype: int64

There are no missing or invalid destination codes.

I was able to answer all the questions with the provided data. However, only for the first question does it specify that we want info about flights in 2013, which is provided in this data. For the rest, we had to assume that it is referring to 2013 data.

In [22]:
df['arr_delay'].mean()

6.89537675731489

The typical delay for the flights in this dataset is 6.89 minutes

In [23]:
df['arr_delay'].count()

327346

Since the number of non-null values of the delay variable is lower than the total number of records, we know that there are missing values of this variable.

In [29]:
dests = df.copy().groupby('dest')
dests.arr_delay.mean().nlargest(3)

dest
CAE    41.764151
TUL    33.659864
OKC    30.619048
Name: arr_delay, dtype: float64

The worst three destinations in terms of longest typical delay are CAE, TUL, and OKC

In [35]:
df.loc[df['month'].isin([12, 1, 2]), 'season'] = 'Winter'
df.loc[df['month'].isin([3, 4, 5]), 'season'] = 'Spring'
df.loc[df['month'].isin([6, 7, 8]), 'season'] = 'Summer'
df.loc[df['month'].isin([9, 10, 11]), 'season'] = 'Fall'

_The above code was written by referencing https://datatofish.com/if-condition-in-pandas-dataframe/_

In [36]:
import matplotlib.pyplot as plt

In [39]:
df.copy().groupby('season').arr_delay.mean().sort_values(ascending=False)

season
Summer    12.989753
Winter     9.037440
Spring     6.808539
Fall      -1.221250
Name: arr_delay, dtype: float64

In [40]:
%matplotlib inline

In [41]:
plt.scatter(df['season'], df['arr_delay'])